name: Build

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo
  QTEST_FUNCTION_TIMEOUT: 60000

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: /usr/bin/g++-10
            name: gcc-10
          - os: ubuntu-latest
            compiler: /usr/bin/clang++-11
            name: clang-11
          #- os: windows-latest
          #  compiler: msvc

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}-${{ matrix.name }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      shell: bash
      run: sudo apt-get install -y --no-install-recommends qtbase5-dev build-essential libc++1-11 libc++-11-dev libc++abi1-11 libc++abi-11-dev dbus dbus-x11

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -DQCORO_ENABLE_ASAN=ON

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure

    - name: Upload build logs on failure
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}-${{ matrix.name }}
        path: build/**
